### ISSUE TITLE
CSS: Mobile styling for web app

### ISSUE THREAD

**Issue by karldreher** [karldreher/KnowYourPorts#1]
CSS needs to be updated to fit mobile devices.  
UI should stay generally the same but the entry box could be much bigger.

**Comment by guilherme-dev** [comment]
Work in progress ;)

**Comment by karldreher** [comment]
@guilherme-dev Thank you!  You have some creative control over how this looks, although as previously mentioned I'd like it to be somewhat consistent with the current desktop view (which can also be changed, as you see fit, see also [issue 2](https://github.com/karldreher/KnowYourPorts/issues/2) ).  Port number should be BIG on mobile devices.  

Ideally, mobile styling should be targetted specifically for mobile devices, leaving the desktop style in place.  Although, I'm sure I don't even have to ask  :)

**Comment by karldreher** [comment]
Still outstanding and leftover from last hacktoberfest if anyone is keen to pick this up again!

**Comment by josiahdahl** [comment]
@karldreher I'd be willing to pick this up - I'll poke around at it tonight and submit something.

**Comment by karldreher** [comment]
@josiahdahl Extremely well polished!  Thanks again, I will learn much from what you've done here.
