### ISSUE TITLE
CSS:  Entry label width to match placeholder text width

### ISSUE THREAD

**Issue by karldreher** [karldreher/KnowYourPorts#14]
"Enter a TCPIP Port Numb" is as far as it gets on my (Desktop) screen.  Width should be at least as long as the text. 

Mobile is now OK as of #1 closure.

**Comment by emorres25** [comment]
Can you please explain again?

**Comment by sandeshghanta** [comment]
I am interested in working on this bug.

**Comment by karldreher** [comment]
This was fixed in #17 by @batraman .  Nice work, thanks for helping the UI along!
