### ISSUE TITLE
Web App: Input Validation

### ISSUE THREAD

**Issue by karldreher** [karldreher/KnowYourPorts#3]
Input is not currently validated; should only accept numerical input.  

This app is not terribly susceptible to compromise, but this is something that should be done anyway.  

On the frontend, this could also add a few features, such as autoswitching keyboard to numpad on mobile, and/or highlighting bad input/disabling submit button.

**Comment by Mikepicker** [comment]
Hi! I've implemented a basic input validation. I've just submitted a pull request [here](https://github.com/karldreher/KnowYourPorts/pull/9).

**Comment by karldreher** [comment]
@Mikepicker This is a really nice, simple implementation.  I will merge this into the main branch.  Thanks for the assistance!
