### ISSUE TITLE
How is this software licensed?

### ISSUE THREAD

**Issue by SpectralCoding** [karldreher/KnowYourPorts#4]
Curious how this software is licensed. If you want to reply to this issue with whatever license you want I'll submit a pull request to make the appropriate changes.

http://choosealicense.com/

I suggest MIT if you want simple and open, or GPLv3 if you want more restrictions on commercial use.

**Comment by karldreher** [comment]
Thank you for documenting this issue, this is something I was considering as I committed it last night and something I wanted to make sure was addressed.  
I believe that GPLv3 will fit the needs of this project best.

**Comment by SpectralCoding** [comment]
I have submitted a pull request: #5
