### ISSUE TITLE
Database Persistence and Feed

### ISSUE THREAD

**Issue by shepherdjay** [karldreher/KnowYourPorts#42]
While implementing sqlalchemy I noticed that the original code and my implementation code recreates the entire database from scratch.

Is this desired behavior? I'm assuming the intent is so that a regular restart of the process will result in new data but it also pulls from a local copy so the data is already out of date.

An additional question I had was around using the XML feed instead of the CSV feed? The XML file seems like it makes it difficult to reason about. (I hate working with XML)

**Comment by shepherdjay** [comment]
I don't mean to disparage XML too much and ElementTree is a fantastic thing to work but it can be a bear sometimes.

**Comment by karldreher** [comment]
Closing this issue, this is working as intended for the time being.
